#pragma once

#include <array>
#include <string>

const auto k_Movies = std::to_array<std::string>({
    "Guardians of the Galaxy",
    "Prometheus",
    "Split",
    "Sing",
    "Suicide Squad",
    "The Great Wall",
    "La La Land",
    "Mindhorn",
    "The Lost City of Z",
    "Passengers",
    "Fantastic Beasts and Where to Find Them",
    "Hidden Figures",
    "Rogue One",
    "Moana",
    "Colossal",
    "The Secret Life of Pets",
    "Hacksaw Ridge",
    "Jason Bourne",
    "Lion",
    "Arrival",
    "Gold",
    "Manchester by the Sea",
    "Hounds of Love",
    "Trolls",
    "Independence Day: Resurgence",
    "Paris pieds nus",
    "Bahubali: The Beginning",
    "Dead Awake",
    "Bad Moms",
    "Assassin's Creed",
    "Why Him ?",
    "Nocturnal Animals",
    "X - Men: Apocalypse",
    "Deadpool",
    "Resident Evil: The Final Chapter",
    "Captain America: Civil War",
    "Interstellar",
    "Doctor Strange",
    "The Magnificent Seven",
    "5 - 25 - 77",
    "Sausage Party",
    "Moonlight",
    "Don't Fuck in the Woods",
    "The Founder",
    "Lowriders",
    "Pirates of the Caribbean: On Stranger Tides",
    "Miss Sloane",
    "Fallen",
    "Star Trek Beyond",
    "The Last Face",
    "Star Wars: Episode VII - The Force Awakens",
    "Underworld: Blood Wars",
    "Mother's Day",
    "John Wick",
    "The Dark Knight",
    "Silence",
    "Don't Breathe",
    "Me Before You",
    "Their Finest",
    "Sully",
    "Batman v Superman: Dawn of Justice",
    "The Autopsy of Jane Doe",
    "The Girl on the Train",
    "Fifty Shades of Grey",
    "The Prestige",
    "Kingsman: The Secret Service",
    "Patriots Day",
    "Mad Max: Fury Road",
    "Wakefield",
    "Deepwater Horizon",
    "The Promise",
    "Allied",
    "A Monster Calls",
    "Collateral Beauty",
    "Zootopia",
    "Pirates of the Caribbean: At World's End",
    "The Avengers",
    "Inglourious Basterds",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Ghostbusters",
    "Inception",
    "Captain Fantastic",
    "The Wolf of Wall Street",
    "Gone Girl",
    "Furious Seven",
    "Jurassic World",
    "Live by Night",
    "Avatar",
    "The Hateful Eight",
    "The Accountant",
    "Prisoners",
    "Warcraft",
    "The Help",
    "War Dogs",
    "Avengers: Age of Ultron",
    "The Nice Guys",
    "Kimi no na wa",
    "The Void",
    "Personal Shopper",
    "The Departed",
    "Legend",
    "Thor",
    "The Martian",
    "Contratiempo",
    "The Man from U.N.C.L.E.",
    "Hell or High Water",
    "The Comedian",
    "The Legend of Tarzan",
    "All We Had",
    "Ex Machina",
    "The Belko Experiment",
    "12 Years a Slave",
    "The Bad Batch",
    "300",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Office Christmas Party",
    "The Neon Demon",
    "Dangal",
    "10 Cloverfield Lane",
    "Finding Dory",
    "Miss Peregrine's Home for Peculiar Children",
    "Divergent",
    "Mike and Dave Need Wedding Dates",
    "Boyka: Undisputed IV",
    "The Dark Knight Rises",
    "The Jungle Book",
    "Transformers: Age of Extinction",
    "Nerve",
    "Mamma Mia!",
    "The Revenant",
    "Fences",
    "Into the Woods",
    "The Shallows",
    "Whiplash",
    "Furious 6",
    "The Place Beyond the Pines",
    "No Country for Old Men",
    "The Great Gatsby",
    "Shutter Island",
    "Brimstone",
    "Star Trek",
    "Diary of a Wimpy Kid",
    "The Big Short",
    "Room",
    "Django Unchained",
    "Ah - ga - ssi",
    "The Edge of Seventeen",
    "Watchmen",
    "Superbad",
    "Inferno",
    "The BFG",
    "The Hunger Games",
    "White Girl",
    "Sicario",
    "Twin Peaks: The Missing Pieces",
    "Aliens vs Predator - Requiem",
    "Pacific Rim",
    "Crazy, Stupid, Love.",
    "Scott Pilgrim vs.the World",
    "Hot Fuzz",
    "Mine",
    "Free Fire",
    "X - Men: Days of Future Past",
    "Jack Reacher: Never Go Back",
    "Casino Royale",
    "Twilight",
    "Now You See Me 2",
    "Woman in Gold",
    "13 Hours",
    "Spectre",
    "Nightcrawler",
    "Kubo and the Two Strings",
    "Beyond the Gates",
    "Her",
    "Frozen",
    "Tomorrowland",
    "Dawn of the Planet of the Apes",
    "Tropic Thunder",
    "The Conjuring 2",
    "Ant - Man",
    "Bridget Jones's Baby",
    "The VVitch: A New - England Folktale",
    "Cinderella",
    "Realive",
    "Forushande",
    "Love",
    "Billy Lynn's Long Halftime Walk",
    "Crimson Peak",
    "Drive",
    "Trainwreck",
    "The Light Between Oceans",
    "Below Her Mouth",
    "Spotlight",
    "Morgan",
    "Warrior",
    "Captain America: The First Avenger",
    "Hacker",
    "Into the Wild",
    "The Imitation Game",
    "Central Intelligence",
    "Edge of Tomorrow",
    "A Cure for Wellness",
    "Snowden",
    "Iron Man",
    "Allegiant",
    "X: First Class",
    "Raw(II)",
    "Paterson",
    "Bridesmaids",
    "The Girl with All the Gifts",
    "San Andreas",
    "Spring Breakers",
    "Transformers",
    "Old Boy",
    "Thor: The Dark World",
    "Gods of Egypt",
    "Captain America: The Winter Soldier",
    "Monster Trucks",
    "A Dark Song",
    "Kick - Ass",
    "Hardcore Henry",
    "Cars",
    "It Follows",
    "The Girl with the Dragon Tattoo",
    "We're the Millers",
    "American Honey",
    "The Lobster",
    "Predators",
    "Maleficent",
    "Rupture",
    "Pan's Labyrinth",
    "A Kind of Murder",
    "Apocalypto",
    "Mission: Impossible - Rogue Nation",
    "The Huntsman: Winter's War",
    "The Perks of Being a Wallflower",
    "Jackie",
    "The Disappointments Room",
    "The Grand Budapest Hotel",
    "The Host",
    "Fury",
    "Inside Out",
    "Rock Dog",
    "Terminator Genisys",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Children of Men",
    "20th Century Women",
    "Spy",
    "The Intouchables",
    "Bonjour Anne",
    "Kynodontas",
    "Straight Outta Compton",
    "The Amazing Spider - Man 2",
    "The Conjuring",
    "The Hangover",
    "Battleship",
    "Rise of the Planet of the Apes",
    "Lights Out",
    "Norman: The Moderate Rise and Tragic Fall of a New York Fixer",
    "Birdman or (The Unexpected Virtue of Ignorance)",
    "Black Swan",
    "Dear White People",
    "Nymphomaniac: Vol.I",
    "Teenage Mutant Ninja Turtles: Out of the Shadows",
    "Knock Knock",
    "Dirty Grandpa",
    "Cloud Atlas",
    "X - Men Origins: Wolverine",
    "Satanic",
    "Skyfall",
    "The Hobbit: An Unexpected Journey",
    "21 Jump Street",
    "Sing Street",
    "Ballerina",
    "Oblivion",
    "22 Jump Street",
    "Zodiac",
    "Everybody Wants Some!!",
    "Iron Man Three",
    "Now You See Me",
    "Sherlock Holmes",
    "Death Proof",
    "The Danish Girl",
    "Hercules",
    "Sucker Punch",
    "Keeping Up with the Joneses",
    "Jupiter Ascending",
    "Masterminds",
    "Iris",
    "Busanhaeng",
    "Pitch Perfect",
    "Neighbors 2: Sorority Rising",
    "The Exception",
    "Man of Steel",
    "The Choice",
    "Ice Age: Collision Course",
    "The Devil Wears Prada",
    "The Infiltrator",
    "There Will Be Blood",
    "The Equalizer",
    "Lone Survivor",
    "The Cabin in the Woods",
    "The House Bunny",
    "She's Out of My League",
    "Inherent Vice",
    "Alice Through the Looking Glass",
    "Vincent N Roxxy",
    "The Fast and the Furious: Tokyo Drift",
    "How to Be Single",
    "The Blind Side",
    "The Babadook",
    "The Hobbit: The Battle of the Five Armies",
    "Harry Potter and the Order of the Phoenix",
    "Snowpiercer",
    "The 5th Wave",
    "The Stakelander",
    "The Visit",
    "Fast Five",
    "Step Up",
    "Lovesong",
    "RocknRolla",
    "In Time",
    "The Social Network",
    "The Last Witch Hunter",
    "Victor Frankenstein",
    "A Street Cat Named Bob",
    "Green Room",
    "Blackhat",
    "Storks",
    "American Sniper",
    "Dallas Buyers Club",
    "Lincoln",
    "Rush",
    "Before I Wake",
    "Silver Linings Playbook",
    "Tracktown",
    "The Fault in Our Stars",
    "Blended",
    "Fast & Furious",
    "Looper",
    "White House Down",
    "Pete's Dragon",
    "Spider - Man 3",
    "The Three Musketeers",
    "Stardust",
    "American Hustle",
    "Jennifer's Body",
    "Midnight in Paris",
    "Lady Macbeth",
    "Joy",
    "The Dressmaker",
    "Cafe Society",
    "Insurgent",
    "Seventh Son",
    "Demain tout commence",
    "The Theory of Everything",
    "This Is the End",
    "About Time",
    "Step Brothers",
    "Clown",
    "Star Trek Into Darkness",
    "Zombieland",
    "Hail, Caesar!",
    "Slumdog Millionaire",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "American Wrestler: The Wizard",
    "The Amazing Spider - Man",
    "Ben - Hur",
    "Sleight",
    "The Maze Runner",
    "Criminal",
    "Wanted",
    "Florence Foster Jenkins",
    "Collide",
    "Black Mass",
    "Creed",
    "Swiss Army Man",
    "The Expendables 3",
    "What We Do in the Shadows",
    "Southpaw",
    "Hush",
    "Bridge of Spies",
    "The Lego Movie",
    "Everest",
    "Pixels",
    "Robin Hood",
    "The Wolverine",
    "John Carter",
    "Keanu",
    "The Gunman",
    "Steve Jobs",
    "Whisky Galore",
    "Grown Ups 2",
    "The Age of Adaline",
    "The Incredible Hulk",
    "Couples Retreat",
    "Absolutely Anything",
    "Magic Mike",
    "Minions",
    "The Black Room",
    "Bronson",
    "Despicable Me",
    "The Best of Me",
    "The Invitation",
    "Zero Dark Thirty",
    "Tangled",
    "The Hunger Games: Mockingjay - Part 2",
    "Vacation",
    "Taken",
    "Pitch Perfect 2",
    "Monsters University",
    "Elle",
    "Mechanic: Resurrection",
    "Tusk",
    "The Headhunter's Calling",
    "Atonement",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Shame",
    "Hanna",
    "The Babysitters",
    "Pride and Prejudice and Zombies",
    "300: Rise of an Empire",
    "London Has Fallen",
    "The Curious Case of Benjamin Button",
    "Sin City: A Dame to Kill For",
    "The Bourne Ultimatum",
    "Srpski film",
    "The Purge: Election Year",
    "3 Idiots",
    "Zoolander 2",
    "World War Z",
    "Mission: Impossible - Ghost Protocol",
    "Let Me Make You a Martyr",
    "Filth",
    "The Longest Ride",
    "The imposible",
    "Kick - Ass 2",
    "Folk Hero & Funny Guy",
    "Oz the Great and Powerful",
    "Brooklyn",
    "Coraline",
    "Blue Valentine",
    "The Thinning",
    "Silent Hill",
    "Dredd",
    "Hunt for the Wilderpeople",
    "Big Hero 6",
    "Carrie",
    "Iron Man 2",
    "Demolition",
    "Pandorum",
    "Olympus Has Fallen",
    "I Am Number Four",
    "Jagten",
    "The Proposal",
    "Get Hard",
    "Just Go with It",
    "Revolutionary Road",
    "The Town",
    "The Boy",
    "Denial",
    "Predestination",
    "Goosebumps",
    "Sherlock Holmes: A Game of Shadows",
    "Salt",
    "Enemy",
    "District 9",
    "The Other Guys",
    "American Gangster",
    "Marie Antoinette",
    "2012",
    "Harry Potter and the Half - Blood Prince",
    "Argo",
    "Eddie the Eagle",
    "The Lives of Others",
    "Pet",
    "Paint It Black",
    "Macbeth",
    "Forgetting Sarah Marshall",
    "The Giver",
    "Triple 9",
    "Perfetti sconosciuti",
    "Angry Birds",
    "Moonrise Kingdom",
    "Hairspray",
    "Safe Haven",
    "Focus",
    "Ratatouille",
    "Stake Land",
    "The Book of Eli",
    "Cloverfield",
    "Point Break",
    "Under the Skin",
    "I Am Legend",
    "Men in Black 3",
    "Super 8",
    "Law Abiding Citizen",
    "Up",
    "Maze Runner: The Scorch Trials",
    "Carol",
    "Imperium",
    "Youth",
    "Mr.Nobody",
    "City of Tiny Lights",
    "Savages",
    "(500) Days of Summer",
    "Movie 43",
    "Gravity",
    "The Boy in the Striped Pyjamas",
    "Shooter",
    "The Happening",
    "Bone Tomahawk",
    "Magic Mike XXL",
    "Easy A",
    "Exodus: Gods and Kings",
    "Chappie",
    "The Hobbit: The Desolation of Smaug",
    "Half of a Yellow Sun",
    "Anthropoid",
    "The Counselor",
    "Viking",
    "Whiskey Tango Foxtrot",
    "Trust",
    "Birth of the Dragon",
    "Elysium",
    "The Green Inferno",
    "Godzilla",
    "The Bourne Legacy",
    "A Good Year",
    "Friend Request",
    "Deja Vu",
    "Lucy",
    "A Quiet Passion",
    "Need for Speed",
    "Jack Reacher",
    "The Do - Over",
    "True Crimes",
    "American Pastoral",
    "The Ghost Writer",
    "Limitless",
    "Spectral",
    "P.S.I Love You",
    "Zipper",
    "Midnight Special",
    "Don't Think Twice",
    "Alice in Wonderland",
    "Chuck",
    "I, Daniel Blake",
    "The Break - Up",
    "Loving",
    "Fantastic Four",
    "The Survivalist",
    "Colonia",
    "The Boy Next Door",
    "The Gift",
    "Dracula Untold",
    "In the Heart of the Sea",
    "Idiocracy",
    "The Expendables",
    "Evil Dead",
    "Sinister",
    "Wreck - It Ralph",
    "Snow White and the Huntsman",
    "Pan",
    "Transformers: Dark of the Moon",
    "Juno",
    "A Hologram for the King",
    "Money Monster",
    "The Other Woman",
    "Enchanted",
    "The Intern",
    "Little Miss Sunshine",
    "Bleed for This",
    "Clash of the Titans",
    "The Finest Hours",
    "Tron",
    "The Hunger Games: Catching Fire",
    "All Good Things",
    "Kickboxer: Vengeance",
    "The Last Airbender",
    "Sex Tape",
    "What to Expect When You're Expecting",
    "Moneyball",
    "Ghost Rider",
    "Unbroken",
    "Immortals",
    "Sunshine",
    "Brave",
    "Adoration",
    "The Drop",
    "She's the Man",
    "Daddy's Home",
    "Let Me In",
    "Never Back Down",
    "Grimsby",
    "Moon",
    "Megamind",
    "Gangster Squad",
    "Blood Father",
    "He's Just Not That Into You",
    "Kung Fu Panda 3",
    "The Rise of the Krays",
    "Handsome Devil",
    "Winter's Bone",
    "Horrible Bosses",
    "Mommy",
    "Hellboy II: The Golden Army",
    "Beautiful Creatures",
    "Toni Erdmann",
    "The Lovely Bones",
    "The Assassination of Jesse James by the Coward Robert Ford",
    "Don Jon",
    "Bastille Day",
    "2307: Winter's Dream",
    "Free State of Jones",
    "Mr.Right",
    "The Secret Life of Walter Mitty",
    "Dope",
    "Underworld Awakening",
    "Antichrist",
    "Friday the 13th",
    "Taken 3",
    "Total Recall",
    "X - Men: The Last Stand",
    "The Escort",
    "The Whole Truth",
    "Night at the Museum: Secret of the Tomb",
    "Love & Other Drugs",
    "The Interview",
    "The Host",
    "Megan Is Missing",
    "Knocked Up",
    "Source Code",
    "Lawless",
    "Unfriended",
    "American Reunion",
    "The Pursuit of Happyness",
    "Relatos salvajes",
    "The Ridiculous 6",
    "Frantz",
    "Viral",
    "Gran Torino",
    "Burnt",
    "Tall Men",
    "Sleeping Beauty",
    "Vampire Academy",
    "Sweeney Todd: The Demon Barber of Fleet Street",
    "Solace",
    "Insidious",
    "Popstar: Never Stop Never Stopping",
    "The Levelling",
    "Public Enemies",
    "Boyhood",
    "Teenage Mutant Ninja Turtles",
    "Eastern Promises",
    "The Daughter",
    "Pineapple Express",
    "The First Time",
    "Gone Baby Gone",
    "The Heat",
    "L'avenir",
    "Anna Karenina",
    "Regression",
    "Ted 2",
    "Pain & Gain",
    "Blood Diamond",
    "Devil's Knot",
    "Child 44",
    "The Hurt Locker",
    "Green Lantern",
    "War on Everyone",
    "The Mist",
    "Escape Plan",
    "Love, Rosie",
    "The DUFF",
    "The Age of Shadows",
    "The Hunger Games: Mockingjay - Part 1",
    "We Need to Talk About Kevin",
    "Love & Friendship",
    "The Mortal Instruments: City of Bones",
    "Seven Pounds",
    "The King's Speech",
    "Hunger",
    "Jumper",
    "Toy Story 3",
    "Tinker Tailor Soldier Spy",
    "Resident Evil: Retribution",
    "Dear Zindagi",
    "Genius",
    "Pompeii",
    "Life of Pi",
    "Hachi: A Dog's Tale",
    "10 Years",
    "I Origins",
    "Live Free or Die Hard",
    "The Matchbreaker",
    "Funny Games",
    "Ted",
    "RED",
    "Australia",
    "Faster",
    "The Neighbor",
    "The Adjustment Bureau",
    "The Hollars",
    "The Judge",
    "Closed Circuit",
    "Transformers: Revenge of the Fallen",
    "La tortue rouge",
    "The Book of Life",
    "Incendies",
    "The Heartbreak Kid",
    "Happy Feet",
    "Entourage",
    "The Strangers",
    "Noah",
    "Neighbors",
    "Nymphomaniac: Vol.II",
    "Wild",
    "Grown Ups",
    "Blair Witch",
    "The Karate Kid",
    "Dark Shadows",
    "Friends with Benefits",
    "The Illusionist",
    "The A - Team",
    "The Guest",
    "The Internship",
    "Paul",
    "This Beautiful Fantastic",
    "The Da Vinci Code",
    "Mr.Church",
    "Hugo",
    "The Blackcoat's Daughter",
    "Body of Lies",
    "Knight of Cups",
    "The Mummy: Tomb of the Dragon Emperor",
    "The Boss",
    "Hands of Stone",
    "El secreto de sus ojos",
    "True Grit",
    "We Are Your Friends",
    "A Million Ways to Die in the West",
    "Only for One Night",
    "Rules Don't Apply",
    "Ouija: Origin of Evil",
    "Percy Jackson: Sea of Monsters",
    "Fracture",
    "Oculus",
    "In Bruges",
    "This Means War",
    "The Road",
    "Lavender",
    "Deuces",
    "Conan the Barbarian",
    "The Fighter",
    "August Rush",
    "Chef",
    "Eye in the Sky",
    "Eagle Eye",
    "The Purge",
    "PK",
    "Ender's Game",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Paper Towns",
    "High - Rise",
    "Quantum of Solace",
    "The Assignment",
    "How to Train Your Dragon",
    "Lady in the Water",
    "The Fountain",
    "Cars 2",
    "31",
    "Final Girl",
    "Chalk It Up",
    "The Man Who Knew Infinity",
    "Unknown",
    "Self / less",
    "Mr.Brooks",
    "Tramps",
    "Before We Go",
    "Captain Phillips",
    "The Secret Scripture",
    "Max Steel",
    "Hotel Transylvania 2",
    "Hancock",
    "Sisters",
    "The Family",
    "Zack and Miri Make a Porno",
    "Ma vie de Courgette",
    "Man on a Ledge",
    "No Strings Attached",
    "Rescue Dawn",
    "Despicable Me 2",
    "A Walk Among the Tombstones",
    "The World's End",
    "Yoga Hosers",
    "Seven Psychopaths",
    "Beowulf",
    "Jack Ryan: Shadow Recruit",
    "1408",
    "The Gambler",
    "Prince of Persia: The Sands of Time",
    "The Spectacular Now",
    "A United Kingdom",
    "USS Indianapolis: Men of Courage",
    "Turbo Kid",
    "Mama",
    "Orphan",
    "To Rome with Love",
    "Fantastic Mr.Fox",
    "Inside Man",
    "I.T.",
    "127 Hours",
    "Annabelle",
    "Wolves at the Door",
    "The Imaginarium of Doctor Parnassus",
    "G.I.Joe: The Rise of Cobra",
    "Christine",
    "Man Down",
    "Crawlspace",
    "Shut In",
    "The Warriors Gate",
    "Grindhouse",
    "Disaster Movie",
    "Rocky Balboa",
    "Diary of a Wimpy Kid: Dog Days",
    "Jane Eyre",
    "Fool's Gold",
    "The Dictator",
    "The Loft",
    "Bacalaureat",
    "You Don't Mess with the Zohan",
    "Exposed",
    "Maudie",
    "Horrible Bosses 2",
    "A Bigger Splash",
    "Melancholia",
    "The Princess and the Frog",
    "Unstoppable",
    "Flight",
    "Home",
    "La migliore offerta",
    "Mean Dreams",
    "42",
    "21",
    "Begin Again",
    "Out of the Furnace",
    "Vicky Cristina Barcelona",
    "Kung Fu Panda",
    "Barbershop: The Next Cut",
    "Terminator Salvation",
    "Freedom Writers",
    "The Hills Have Eyes",
    "Changeling",
    "Remember Me",
    "Koe no katachi",
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
    "Locke",
    "The 9th Life of Louis Drax",
    "Horns",
    "Indignation",
    "The Stanford Prison Experiment",
    "Diary of a Wimpy Kid: Rodrick Rules",
    "Mission: Impossible III",
    "En man som heter Ove",
    "Dragonball Evolution",
    "Red Dawn",
    "One Day",
    "Life as We Know It",
    "28 Weeks Later",
    "Warm Bodies",
    "Blue Jasmine",
    "G.I.Joe: Retaliation",
    "Wrath of the Titans",
    "Shin Gojira",
    "Saving Mr.Banks",
    "Transcendence",
    "Rio",
    "Equals",
    "Babel",
    "The Tree of Life",
    "The Lucky One",
    "Piranha 3D",
    "50 / 50",
    "The Intent",
    "This Is 40",
    "Real Steel",
    "Sex and the City",
    "Rambo",
    "Planet Terror",
    "Concussion",
    "The Fall",
    "The Ugly Truth",
    "Bride Wars",
    "Sleeping with Other People",
    "Snakes on a Plane",
    "What If",
    "How to Train Your Dragon 2",
    "RoboCop",
    "In Dubious Battle",
    "Hello, My Name Is Doris",
    "Ocean's Thirteen",
    "Slither",
    "Contagion",
    "Il racconto dei racconti - Tale of Tales",
    "I Am the Pretty Thing That Lives in the House",
    "Bridge to Terabithia",
    "Coherence",
    "Notorious",
    "Goksung",
    "The Expendables 2",
    "The Girl Next Door",
    "Perfume: The Story of a Murderer",
    "The Golden Compass",
    "Centurion",
    "Scouts Guide to the Zombie Apocalypse",
    "17 Again",
    "No Escape",
    "Superman Returns",
    "The Twilight Saga: Breaking Dawn - Part 1",
    "Precious",
    "The Sea of Trees",
    "Good Kids",
    "The Master",
    "Footloose",
    "If I Stay",
    "The Ticket",
    "Detour",
    "The Love Witch",
    "Talladega Nights: The Ballad of Ricky Bobby",
    "The Human Centipede(First Sequence)",
    "Super",
    "The Siege of Jadotville",
    "Up in the Air",
    "The Midnight Meat Train",
    "The Twilight Saga: Eclipse",
    "Transpecos",
    "What's Your Number?",
    "Riddick",
    "Triangle",
    "The Butler",
    "King Cobra",
    "After Earth",
    "Kicks",
    "Me and Earl and the Dying Girl",
    "The Descendants",
    "Sex and the City 2",
    "The Kings of Summer",
    "Death Race",
    "That Awkward Moment",
    "Legion",
    "End of Watch",
    "3 Days to Kill",
    "Lucky Number Slevin",
    "Trance",
    "Into the Forest",
    "The Other Boleyn Girl",
    "I Spit on Your Grave",
    "Custody",
    "Inland Empire",
    "The Walk",
    "Wrecker",
    "The Lone Ranger",
    "Texas Chainsaw 3D",
    "Disturbia",
    "Rock of Ages",
    "Scream 4",
    "Queen of Katwe",
    "My Big Fat Greek Wedding 2",
    "Dark Places",
    "Amateur Night",
    "It's Only the End of the World",
    "The Skin I Live In",
    "Miracles from Heaven",
    "Annie",
    "Across the Universe",
    "Let's Be Cops",
    "Max",
    "Your Highness",
    "Final Destination 5",
    "Endless Love",
    "Martyrs",
    "Selma",
    "Underworld: Rise of the Lycans",
    "Taare Zameen Par",
    "Take Me Home Tonight",
    "Resident Evil: Afterlife",
    "Project X",
    "Secret in Their Eyes",
    "Hostel: Part II",
    "Step Up 2: The Streets",
    "Search Party",
    "Nine Lives" });
